package com.trangiaphat.report;

import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Builds CSV / JSON business reports from a generic list of "row" objects.
 * Used for exporting project lists, consultation requests (leads) and
 * cost estimates from the admin dashboard.
 */
public final class ReportGenerator {

    private ReportGenerator() {}

    /** Renders rows as RFC 4180-ish CSV text (UTF-8, comma separated, quoted fields). */
    public static String toCsv(String title, List<String> columns, List<JsonValue> rows) {
        StringBuilder sb = new StringBuilder();
        sb.append("# ").append(title).append('\n');
        sb.append("# Generated by TGP Report Service (Java) at ").append(Instant.now()).append('\n');

        List<String> effectiveColumns = columns;
        if (effectiveColumns == null || effectiveColumns.isEmpty()) {
            effectiveColumns = inferColumns(rows);
        }

        sb.append(String.join(",", quoteAll(effectiveColumns))).append('\n');

        for (JsonValue row : rows) {
            Map<String, JsonValue> obj = row.asObject();
            List<String> cells = new ArrayList<>();
            for (String col : effectiveColumns) {
                JsonValue v = obj.get(col);
                cells.add(csvQuote(v == null ? "" : v.asString()));
            }
            sb.append(String.join(",", cells)).append('\n');
        }
        return sb.toString();
    }

    /** Renders a small metadata-wrapped JSON report (row count, generated_at, rows). */
    public static String toJsonReport(String title, List<JsonValue> rows) {
        StringBuilder sb = new StringBuilder();
        sb.append("{\n");
        sb.append("  \"title\": \"").append(jsonEscape(title)).append("\",\n");
        sb.append("  \"generated_at\": \"").append(Instant.now()).append("\",\n");
        sb.append("  \"row_count\": ").append(rows.size()).append(",\n");
        sb.append("  \"rows\": [\n");
        for (int i = 0; i < rows.size(); i++) {
            sb.append(renderObjectIndented(rows.get(i), "    "));
            if (i < rows.size() - 1) sb.append(",");
            sb.append('\n');
        }
        sb.append("  ]\n");
        sb.append("}\n");
        return sb.toString();
    }

    private static String renderObjectIndented(JsonValue row, String indent) {
        Map<String, JsonValue> obj = row.asObject();
        StringBuilder sb = new StringBuilder();
        sb.append(indent).append("{");
        int i = 0;
        for (Map.Entry<String, JsonValue> e : obj.entrySet()) {
            if (i > 0) sb.append(", ");
            sb.append("\"").append(jsonEscape(e.getKey())).append("\": ");
            JsonValue v = e.getValue();
            if (v.type == JsonValue.Type.NUMBER) {
                sb.append(v.asString());
            } else if (v.type == JsonValue.Type.BOOLEAN) {
                sb.append(v.asString());
            } else {
                sb.append("\"").append(jsonEscape(v.asString())).append("\"");
            }
            i++;
        }
        sb.append("}");
        return sb.toString();
    }

    private static List<String> inferColumns(List<JsonValue> rows) {
        Set<String> cols = new LinkedHashSet<>();
        for (JsonValue row : rows) {
            cols.addAll(row.asObject().keySet());
        }
        return new ArrayList<>(cols);
    }

    private static List<String> quoteAll(List<String> values) {
        List<String> out = new ArrayList<>();
        for (String v : values) out.add(csvQuote(v));
        return out;
    }

    private static String csvQuote(String value) {
        String escaped = value.replace("\"", "\"\"");
        return "\"" + escaped + "\"";
    }

    private static String jsonEscape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n");
    }
}
